# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151217_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='object_id',
        ),
        migrations.AddField(
            model_name='file',
            name='permission',
            field=models.CharField(choices=[['0', 'public'], ['1', 'users']], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='permission',
            field=models.CharField(choices=[['0', 'public'], ['1', 'users']], default='1', max_length=1),
        ),
    ]
