# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151217_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='permission',
        ),
    ]
