# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20151217_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
