# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151217_1555'),
        ('college', '0002_auto_20151217_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.File'),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.File'),
        ),
        migrations.AddField(
            model_name='historicalcollege',
            name='cover',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.File'),
        ),
        migrations.AddField(
            model_name='historicalcollege',
            name='logo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.File'),
        ),
        migrations.AlterField(
            model_name='college',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollege',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollege',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
