# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20151217_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='email_domains',
            field=models.ManyToManyField(blank=True, to='account.EmailDomain'),
        ),
        migrations.AlterField(
            model_name='college',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
